apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h4ueq3oxv-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:9acc9c00ae9c7b358245f03b3226daab6da73f4b@sha256:3096a0960028677a8b7be4b4a4038852abe456f10b08fac9c9b53e13a053bb64
          name: container-image
